### PR TITLE
Support React 18 as peer dependency

### LINKED ISSUE #135: add peerDependency support for react 18

### PR DESCRIPTION
**Pull request by anttispitkanen**
* Without this, when installing in a project with React 18, `npm install` would fail with unmet peer dependencies error (https://docs.npmjs.com/cli/v9/commands/npm-ci)
* Resolves https://github.com/react-container-query/react-container-query/issues/135

### CODE REVIEW

**Comment by jinbeeahn** [comment]
will there be any updates from author/contributors regarding this PR? would be really nice to have this gets fixed ASAP

**Comment by d6u** [comment]
Hey sorry, I'm one of the contributors who has been absent for years. This PR looks like harmless, so let me try to merge.

**Comment by d6u** [comment]
However... I don't seem to remember how to publish a version of the NPM module now. So let me figure it out this week...

**Comment by d6u** [comment]
Publish a new version. See https://github.com/react-container-query/react-container-query/issues/137

**Pull request merged**
