### PR TITLE
Allow applyContainerQuery to take Stateless component as component

### PR DESCRIPTION
**Pull request by sammkj**

### CODE REVIEW

**Comment by d6u** [comment]
Can you follow to allow me to push to you PR? I want to add a test case. Thanks!

**Comment by sammkj** [comment]
Added you to the repo. Also, I think that the definition is missing a few other things. I will push some commits now

**Comment by sammkj** [comment]
The reason for the new commit is because if I try to do the following, TS will throw error:

```
// component.js
const Component = ({
  containerQuery,
}) => (
  <div>
    component
  </div>
);

const query = {
  tablet: {
    width: 700,
    height: 700,
}

export default applyContainerQuery(Component, query);

// index.js
import Component from "./component.js"

<Component />   <====== TS will throw `containerQuery` is missing.
```

So the new commit fixes this.

**Comment by d6u** [comment]
Ha, thanks! I meant to add this link https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/, but allow the whole repo works for me, too.

**Comment by d6u** [comment]
I will take a look later today.

**Pull request merged**
