### PR TITLE
Move @types packages to devDependencies

### PR DESCRIPTION
**Pull request by brentertz**
#### What does this PR do?

Move @types packages to `devDependencies`

#### Any background context you want to provide?

Currently unable to install package from npm.

screen shot 2016-11-10 at 11 03 25 am

### CODE REVIEW

**Comment by brentertz** [comment]
I have found a workaround, which is to place `@types:registry=https://registry.npmjs.org` in my `.npmrc`.

**Comment by banderson** [comment]
I also just ran into this issue, seems like those should definitely be `devDependencies`, right @d6u ?

**Comment by d6u** [comment]
@brentertz @brentertz Sorry for the late reply. This is interesting. Why `@types` package cannot be installed? Have you tried other `@types` package just to make sure it's not a local setup problem? E.g. https://www.npmjs.com/package/@types/lodash?

**Comment by brentertz** [comment]
No worries on the delay...  I failed to mention that I use a local npm repo, Artifactory, which has since been updated and now supports scoped packages.

Our organization would however like to use yarn as a faster alternative to npm, but unfortunately this package will not install via yarn due to the @types dependency.  I am assuming that scoped packages are not yet supported in yarn.

Regardless of my unique context above, the @types packages in your repo appear to be devDependencies.

**Comment by d6u** [comment]
@brentertz thanks for the context. I'm going to close this because I've moved them in another place. Please try it out and let me know how it works with your use case :)

**Comment by d6u** [comment]
Also FYI, please checkout the newest README because I've broken the API since 0.6. It has quite a lot change if you've been using this since 0.6.

**Comment by brentertz** [comment]
@d6u I can confirm that this now works for use case.  Thanks!

**Pull request closed without merging**
